# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=ouss1234

# JWT
security.jwt.secret-key=N9gPK4qwZJU8VylXklZ69Y/jvGNcQ/2vblRfdRWTuD8=
security.jwt.expiration-time=3600000

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.topic=test-topic
spring.kafka.consumer.group-id=my-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest

# Mail (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=oussematrimech@gmail.com
spring.mail.password=xhtq onsx egqz gcyd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true